"""Export every node of the food/music hierarchies in three level columns."""
from project_paths import resource_path as _paper_path, resource_location as _paper_location
from pathlib import Path
import csv
import json

ROOT = _paper_path(__file__).resolve().parents[2]
SOURCE = ROOT / 'full_experiments/results/gemini_131k_hierarchical_families'
OUTPUT = SOURCE / 'compact_main_text'


def tex(text):
    replacements = {'&': r'\&', '%': r'\%', '_': r'\_', '#': r'\#', '$': r'\$'}
    return ''.join(replacements.get(character, character) for character in text)


def main():
    OUTPUT.mkdir(exist_ok=True)
    lines = [r'% Generated by scripts/hierarchy/export_compact_food_music_table.py.',
             r'\begingroup', r'\scriptsize', r'\setlength{\tabcolsep}{2pt}',
             r'\renewcommand{\arraystretch}{1.06}',
             r'\begin{tabularx}{\linewidth}{@{}>{\raggedright\arraybackslash}p{0.12\linewidth}>{\raggedright\arraybackslash}p{0.22\linewidth}>{\raggedright\arraybackslash}X@{}}',
             r'\toprule', r'\textbf{Level 1} & \textbf{Level 2} & \textbf{Level 3} \\', r'\midrule']
    rows = []
    specs = [('food_illustration', 10077, 'Food'), ('music_medium', 33809, 'Music')]
    for domain, (stem, root_id, root_label) in enumerate(specs):
        groups = json.loads((SOURCE / f'{stem}_selection.json').read_text())
        with (SOURCE / f'{stem}_edges.csv').open() as handle:
            edges = {(int(r['parent_feature']), int(r['child_feature'])) for r in csv.DictReader(handle)}
        retained = set()
        if domain:
            lines.append(r'\midrule')
        for i, (parent, label, children) in enumerate(groups):
            root = rf'\multirow[t]{{{len(groups)}}}{{*}}{{\textbf{{{tex(root_label)}}}}}' if i == 0 else ''
            leaves = '; '.join(tex(child_label) for _, child_label in children)
            lines.append(f'{root} & {tex(label)} & {leaves} ' + r'\\')
            if i < len(groups) - 1:
                lines.append(r'\addlinespace[2pt]')
            retained.add((root_id, parent))
            retained.update((parent, child) for child, _ in children)
            rows.append(dict(level_1_feature=root_id, level_1_label=root_label,
                             level_2_feature=parent, level_2_label=label,
                             level_3_features=children))
        assert retained == edges
        assert len({node for edge in retained for node in edge}) == 33
    assert len(rows) == 12
    lines += [r'\bottomrule', r'\end{tabularx}', r'\endgroup', '']
    (OUTPUT / 'food_music_hierarchies_table.tex').write_text('\n'.join(lines))
    (OUTPUT / 'table_rows.json').write_text(json.dumps(rows, indent=2, ensure_ascii=False) + '\n')
    print('Exported 12 branch rows, preserving all 66 features and 64 parent-child relationships.')


if __name__ == '__main__':
    main()
