"""Render the shared text and paired-activation table layout."""

from __future__ import annotations
from project_paths import resource_path as _paper_path, resource_location as _paper_location

import unicodedata

from pathlib import Path

ROOT = _paper_path(__file__).resolve().parents[1]

PACKAGE = ROOT / 'full_experiments/plots/platonic_features_131k_pearson'

COLORS = {'gemini': ('orange', 'FF8000'), 'nemotron': ('orange', 'FF8000')}

COLOR_MAX = 0.15

EXCERPT_CHARACTERS = 96

def escape_tex(text):
    replacements = {'\\': r'\textbackslash{}', '&': r'\&', '%': r'\%', '$': r'\$', '#': r'\#',
                    '_': r'\_', '{': r'\{', '}': r'\}', '~': r'\textasciitilde{}', '^': r'\textasciicircum{}'}
    return ''.join(replacements.get(c, c) for c in text)

def clean_display_text(text):
    """Repair UTF-8 bytes misread as Latin-1/CP1252 without losing valid Unicode."""
    for _ in range(3):
        result, i, changed = [], 0, False
        while i < len(text):
            lead = ord(text[i])
            size = 2 if 0xC2 <= lead <= 0xDF else 3 if 0xE0 <= lead <= 0xEF else 4 if 0xF0 <= lead <= 0xF4 else 0
            repaired = None
            if size and i + size <= len(text):
                chunk = text[i:i + size]
                for encoding in ('latin-1', 'cp1252'):
                    try:
                        candidate = chunk.encode(encoding).decode('utf-8')
                    except (UnicodeEncodeError, UnicodeDecodeError):
                        continue
                    if len(candidate) == 1:
                        repaired = candidate
                        break
            if repaired is not None:
                result.append(repaired)
                i += size
                changed = True
            else:
                result.append(text[i])
                i += 1
        text = ''.join(result)
        if not changed:
            break
    punctuation = {
        '\u2018': "'", '\u2019': "'", '\u201a': "'", '\u201b': "'",
        '\u201c': '"', '\u201d': '"', '\u201e': '"', '\u201f': '"',
        '\u2013': '-', '\u2014': '--', '\u2026': '...', '\u00a0': ' ',
    }
    text = ''.join(punctuation.get(c, c) for c in text)
    return ''.join(' ' if c.isspace() else c for c in text
                   if c.isspace() or (unicodedata.category(c) not in ('Cc', 'Cs')
                                     and c not in ('\ufffd', '\ufeff', '\u200b', '\u2060')))

def excerpt(text):
    text = ' '.join(clean_display_text(text).split()) or '[EMPTY]'
    if len(text) > EXCERPT_CHARACTERS:
        text = text[:EXCERPT_CHARACTERS - 3].rstrip() + '...'
    return text

def percent(value):
    return max(0, min(100, round(100 * value / COLOR_MAX)))

def activation_cell(value, model):
    return rf'\cellcolor{{{COLORS[model][0]}!{percent(value)}}}{value:.3f}'

def caption(pair):
    return (f"{escape_tex(pair['interpretation'])}. "
            rf"Pearson $r={pair['pearson']:.3f}$.")

def render_table(pair, rows):
    lines = [
        '% Generated by scripts/example_table.py.',
        '% Requires booktabs, tabularx, array, caption, and xcolor[table] (or xcolor plus colortbl).',
        '% Samples and paired activations are copied from main_examples/selection_and_examples.json.',
        '% Exactly three columns; 96-character excerpts; the mid-table rule separates sample origins.',
        '% Text cells are grouped to protect leading square brackets after row breaks.',
    ]
    for name, color in dict(COLORS.values()).items():
        lines.append(rf'\providecolor{{{name}}}{{HTML}}{{{color}}}')
    lines += [r'\begin{table*}[tp]', r'\centering', r'\scriptsize',
              r'\captionsetup{font=small,skip=4pt}', r'\setlength{\tabcolsep}{4pt}',
              r'\renewcommand{\arraystretch}{1.0}', r'\caption{' + caption(pair) + '}',
              rf"\label{{tab:platonic-pearson-semantic-combined-{pair['paper_example_index']}}}",
              r'\begin{tabularx}{\textwidth}{>{\raggedright\arraybackslash}X >{\centering\arraybackslash}p{1.35cm} >{\centering\arraybackslash}p{1.35cm}}',
              r'\toprule',
              rf"\textbf{{Text}} & \textbf{{Gemini {pair['gemini_feature']}}} & \textbf{{Nemotron {pair['nemotron_feature']}}} " + r'\\',
              r'\midrule']
    sample_boundary = len(pair['gemini_examples'])
    for i, row in enumerate(rows):
        if i == sample_boundary:
            lines.append(r'\midrule')
        # Match the original table formatter's treatment of literal math/LaTeX text.
        text = row['excerpt'].replace('\\', '').replace('$', '').replace('{', '(').replace('}', ')')
        # Group the first cell so a leading '[' cannot become the optional
        # argument of the preceding row's \\ command (\\@argarraycr).
        lines.append('{' + escape_tex(text) + '}' + ' & ' + activation_cell(row['gemini_activation'], 'gemini')
                     + ' & ' + activation_cell(row['nemotron_activation'], 'nemotron') + ' ' + r'\\')
    lines += [r'\bottomrule', r'\end{tabularx}', r'\end{table*}', '']
    return '\n'.join(lines)
